### ISSUE TITLE
ボールドの誤変換？

### ISSUE THREAD

**Issue by suzukin** [takahashim/md2review#9]
PRじゃなくてスミマセン。使用中に予期せぬ変換がありましたのでお伝えします。確かにMarkdownの文法的には誤りではなさそうなのですが、これはどうやって回避するのがいいんですかね…...。

元：openstack_user_config.yml
結果：openstack@{user}config.yml
期待する変換：openstack_user_config.yml

**Comment by takahashim** [comment]
単語中の`_`をマークアップと解釈せずに無視してほしい場合、 `md2review --parse-no-intra-emphasis foo.md` というように、`--parse-no-intra-emphasis ` オプションをつけて実行してください。

このオプションをつける場合、強調として変換してほしい部分には、 `_foo_` などの記法の前後に空白を入れるようにしてください。

**Comment by suzukin** [comment]
ありがとうございます！ うまくいきました。
